[package]
name = "map_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
nannou = "0.19.0"
ron = "0.8.1"

rand.workspace = true
glam.workspace = true
serde.workspace = true

shared.path = "../shared"
thiserror = "1.0.63"
