[package]
name = "map-viewer"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
engine = { path = "../engine" }

nannou = "0.19.0"
ron = "0.8.1"
glam.workspace = true
rand.workspace = true

serde.workspace = true
thiserror = "1"
nannou_egui = "0.19.0"
