[package]
name = "map-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
engine = { path = "../engine" }

nannou = "0.19.0"
ron = "0.8.1"

glam.workspace = true
rand.workspace = true

serde.workspace = true
thiserror = "1"
