[workspace]
resolver = "2"
members = ["engine", "server"]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.dependencies]
glam = { version = "0.29.0", features = ["serde"] }
turborand = "0.10.1"
petgraph = "0.6.5"

tokio = { version = "1", features = ["full"] }

async-channel = "2"
async-broadcast = "0.7.1"

serde = { version = "1", features = ["derive"] }
serde_json = "1.0.127"
internment = { version = "0.8.5", features = ["serde"] }

tracing = "0.1.40"
tracing-subscriber = "0.3.18"
thiserror = "1.0.63"

[workspace.dependencies.clap]
version = "4"
default-features = false
features = ["std", "help", "usage", "error-context", "suggestions", "derive"]
