[package]
name = "engine"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
glam.workspace = true
rand.workspace = true
serde_json.workspace = true

serde.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true
