[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
glam.workspace = true
rand.workspace = true

serde.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true
