[package]
name = "calculator"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
glam.workspace = true
inquire = "0.7.5"
