[package]
name = "server"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
engine = { path = "../engine" }

axum = { version = "0.7.5", features = ["multipart"] }
reqwest = { version = "0.12.5", features = ["multipart"] }
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.23.1"

async-openai = "0.23.4"
tower-http = { version = "0.5.2", features = ["cors", "fs", "trace"] }

futures-util = "0.3.30"

glam.workspace = true
rand.workspace = true

serde.workspace = true
serde_json = "1"

dotenv = "0.15.0"
tracing.workspace = true
tracing-subscriber.workspace = true
