[workspace]
resolver = "2"
members = ["map_viewer", "server", "shared"]

[workspace.dependencies]
serde = { version = "1.0.207", features = ["derive"] }
glam = { version = "0.28.0", features = ["serde"] }
rand = "0.8.5"
