[package]
name = "editor"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
engine = { path = "../engine" }

clap.workspace = true
glam.workspace = true
serde.workspace = true

nannou = "0.19.0"
nannou_egui = "0.19.0"
ron = "0.8.1"
serde_json = "1"
