[package]
name = "editor"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[[bin]]
name = "watcher"
path = "src/watcher.rs"

[dependencies]
engine = { path = "../engine" }

clap.workspace = true
glam.workspace = true
serde.workspace = true
serde_json.workspace = true

mlua = { version = "0.10.3", features = ["lua54", "serialize"] }
nannou = "0.19.0"
nannou_egui = "0.19.0"
ron = "0.8.1"
