[package]
name = "editor"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
engine = { path = "../engine" }

glam.workspace = true
turborand.workspace = true

serde.workspace = true
serde_json = "1"
internment.workspace = true

thiserror.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true
ron = "0.8.1"
nannou = "0.19.0"
nannou_egui = "0.19.0"
