// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AircraftState } from "./AircraftState";
import type { AircraftTargets } from "./AircraftTargets";
import type { FlightPlan } from "./FlightPlan";
import type { FlightSegment } from "./FlightSegment";
import type { TCAS } from "./TCAS";

export type Aircraft = { id: string, is_colliding: boolean, pos: [number, number], speed: number, heading: number, altitude: number, state: AircraftState, target: AircraftTargets, tcas: TCAS, flight_plan: FlightPlan, frequency: number, segment: FlightSegment, accepted: boolean, };
