// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LandingState } from "./LandingState";
import type { Node } from "./Node";
import type { Runway } from "./Runway";
import type { TaxiingState } from "./TaxiingState";

export type AircraftState = { "type": "flying" } | { "type": "landing", "value": { runway: Runway, state: LandingState, } } | { "type": "taxiing", "value": { current: Node<[number, number]>, waypoints: Array<Node<[number, number]>>, state: TaxiingState, } } | { "type": "parked", "value": { at: Node<[number, number]>, } };
