// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Frequencies } from "./Frequencies";
import type { Runway } from "./Runway";
import type { Taxiway } from "./Taxiway";
import type { Terminal } from "./Terminal";

export type Airport = { id: string, frequencies: Frequencies, center: [number, number], runways: Array<Runway>, taxiways: Array<Taxiway>, terminals: Array<Terminal>, };
