// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Airport } from "./Airport";

export type Airspace = { id: string, pos: [number, number], radius: number, airports: Array<Airport>, auto: boolean, };
