// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";
import type { VORData } from "./VORData";

export type FlightPlan = { arriving: string, departing: string, waypoints: Array<Node<VORData>>, waypoint_index: number, follow: boolean, speed: number, altitude: number, };
