// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * FlightSegment denotes the exact segment of flight that an aircraft is in.
 *
 * This is simply a flag for denoting the segment of flight and does not
 * contain any data or further information. [`AircraftState`] is the primary
 * holder of state and data for an aircraft.
 */
export type FlightSegment = "parked" | "taxi-dep" | "takeoff" | "departure" | "cruise" | "arrival" | "approach" | "land" | "taxi-arr";
