// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LandingState = "before-turn" | "turning" | "correcting" | "localizer" | "glideslope" | "touchdown" | "go-around";
