// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeBehavior } from "./NodeBehavior";
import type { NodeKind } from "./NodeKind";

export type Node<T> = { name: string, kind: NodeKind, behavior: NodeBehavior, data: T, };
