// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Duration } from "./Duration";

export type OutgoingCommandReply = { id: string, frequency: number, reply: string, created: Duration, };
