// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Runway = { id: string, pos: [number, number], heading: number, length: number, };
