// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gate } from "./Gate";
import type { Line } from "./Line";

export type Terminal = { id: string, a: [number, number], b: [number, number], c: [number, number], d: [number, number], gates: Array<Gate>, apron: Line, };
