// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Airspace } from "./Airspace";
import type { Node } from "./Node";

export type World = { airspaces: Array<Airspace>, waypoints: Array<Node<[number, number]>>, };
